version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - todo-net

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - todo-net

networks:
  todo-net: