version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://todo_user:todo_pass@db:5432/todo_db
    networks:
      - todo-net

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - todo-net

  db:
    image: postgres:15
    container_name: todo_db
    environment:
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_pass
      - POSTGRES_DB=todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo-net

volumes:
  pgdata:

networks:
  todo-net: